// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"net/http"
)

// AuthAPIRouter defines the required methods for binding the api requests to a responses for the AuthAPI
// The AuthAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AuthAPIServicer to perform the required actions, then write the service results to the http response.
type AuthAPIRouter interface {
	AuthAthleteProfilePost(http.ResponseWriter, *http.Request)
	AuthAthleteTeamPost(http.ResponseWriter, *http.Request)
	AuthCancelInvitePost(http.ResponseWriter, *http.Request)
	AuthChangePasswordPost(http.ResponseWriter, *http.Request)
	AuthCreateInviteCodePost(http.ResponseWriter, *http.Request)
	AuthGetAllInvitesGet(http.ResponseWriter, *http.Request)
	AuthGetInviteDetailsPost(http.ResponseWriter, *http.Request)
	AuthLoginPost(http.ResponseWriter, *http.Request)
	AuthRegisterAthletePost(http.ResponseWriter, *http.Request)
	AuthRegisterInvitePost(http.ResponseWriter, *http.Request)
}

// BiometricsAPIRouter defines the required methods for binding the api requests to a responses for the BiometricsAPI
// The BiometricsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a BiometricsAPIServicer to perform the required actions, then write the service results to the http response.
type BiometricsAPIRouter interface {
	BiometricsPost(http.ResponseWriter, *http.Request)
}

// TeamsAPIRouter defines the required methods for binding the api requests to a responses for the TeamsAPI
// The TeamsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a TeamsAPIServicer to perform the required actions, then write the service results to the http response.
type TeamsAPIRouter interface {
	TeamAthleteRemovePost(http.ResponseWriter, *http.Request)
	TeamsAthletesPost(http.ResponseWriter, *http.Request)
	TeamsCoachesPost(http.ResponseWriter, *http.Request)
	TeamsCreatePost(http.ResponseWriter, *http.Request)
	TeamsGet(http.ResponseWriter, *http.Request)
	TeamsJoinPost(http.ResponseWriter, *http.Request)
	TeamsJoinRequestIdApprovePost(http.ResponseWriter, *http.Request)
	TeamsJoinRequestIdRejectPost(http.ResponseWriter, *http.Request)
}

// TrainingAPIRouter defines the required methods for binding the api requests to a responses for the TrainingAPI
// The TrainingAPIRouter implementation should parse necessary information from the http request,
// pass the data to a TrainingAPIServicer to perform the required actions, then write the service results to the http response.
type TrainingAPIRouter interface {
	TrainingPlansItemsItemIdDelete(http.ResponseWriter, *http.Request)
	TrainingPlansItemsItemIdOverridePost(http.ResponseWriter, *http.Request)
	TrainingPlansPlanIdAssignPost(http.ResponseWriter, *http.Request)
	TrainingPlansPlanIdItemsPost(http.ResponseWriter, *http.Request)
	TrainingPlansPost(http.ResponseWriter, *http.Request)
}

// AuthAPIServicer defines the api actions for the AuthAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AuthAPIServicer interface {
	AuthAthleteProfilePost(context.Context, AthleteProfileRequest) (ImplResponse, error)
	AuthAthleteTeamPost(context.Context, AthleteProfileRequest) (ImplResponse, error)
	AuthCancelInvitePost(context.Context, InviteCancelRequest) (ImplResponse, error)
	AuthChangePasswordPost(context.Context, AuthChangePasswordPostRequest) (ImplResponse, error)
	AuthCreateInviteCodePost(context.Context, InviteCreateRequest) (ImplResponse, error)
	AuthGetAllInvitesGet(context.Context) (ImplResponse, error)
	AuthGetInviteDetailsPost(context.Context, InviteDetailsRequest) (ImplResponse, error)
	AuthLoginPost(context.Context, LoginRequest) (ImplResponse, error)
	AuthRegisterAthletePost(context.Context, AthleteRegisterRequest) (ImplResponse, error)
	AuthRegisterInvitePost(context.Context, InviteRegisterRequest) (ImplResponse, error)
}

// BiometricsAPIServicer defines the api actions for the BiometricsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type BiometricsAPIServicer interface {
	BiometricsPost(context.Context, BiometricInput) (ImplResponse, error)
}

// TeamsAPIServicer defines the api actions for the TeamsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type TeamsAPIServicer interface {
	TeamAthleteRemovePost(context.Context, AthleteProfileRequest) (ImplResponse, error)
	TeamsAthletesPost(context.Context, TeamRequest) (ImplResponse, error)
	TeamsCoachesPost(context.Context, TeamRequest) (ImplResponse, error)
	TeamsCreatePost(context.Context, TeamCreateRequest) (ImplResponse, error)
	TeamsGet(context.Context) (ImplResponse, error)
	TeamsJoinPost(context.Context, TeamsJoinPostRequest) (ImplResponse, error)
	TeamsJoinRequestIdApprovePost(context.Context, int32) (ImplResponse, error)
	TeamsJoinRequestIdRejectPost(context.Context, int32) (ImplResponse, error)
}

// TrainingAPIServicer defines the api actions for the TrainingAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type TrainingAPIServicer interface {
	TrainingPlansItemsItemIdDelete(context.Context, int32) (ImplResponse, error)
	TrainingPlansItemsItemIdOverridePost(context.Context, int32, TrainingPlansItemsItemIdOverridePostRequest) (ImplResponse, error)
	TrainingPlansPlanIdAssignPost(context.Context, int32, TrainingPlansPlanIdAssignPostRequest) (ImplResponse, error)
	TrainingPlansPlanIdItemsPost(context.Context, int32, TrainingPlansPlanIdItemsPostRequest) (ImplResponse, error)
	TrainingPlansPost(context.Context, TrainingPlansPostRequest) (ImplResponse, error)
}
