// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// BiometricsAPIController binds http requests to an api service and writes the service results to the http response
type BiometricsAPIController struct {
	service      BiometricsAPIServicer
	errorHandler ErrorHandler
}

// BiometricsAPIOption for how the controller is set up.
type BiometricsAPIOption func(*BiometricsAPIController)

// WithBiometricsAPIErrorHandler inject ErrorHandler into controller
func WithBiometricsAPIErrorHandler(h ErrorHandler) BiometricsAPIOption {
	return func(c *BiometricsAPIController) {
		c.errorHandler = h
	}
}

// NewBiometricsAPIController creates a default api controller
func NewBiometricsAPIController(s BiometricsAPIServicer, opts ...BiometricsAPIOption) *BiometricsAPIController {
	controller := &BiometricsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the BiometricsAPIController
func (c *BiometricsAPIController) Routes() Routes {
	return Routes{
		"BiometricsPost": Route{
			strings.ToUpper("Post"),
			"/api/v1/biometrics",
			c.BiometricsPost,
		},
	}
}

// BiometricsPost - Ввод биометрических данных спортсменом
func (c *BiometricsAPIController) BiometricsPost(w http.ResponseWriter, r *http.Request) {
	biometricInputParam := BiometricInput{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&biometricInputParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBiometricInputRequired(biometricInputParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBiometricInputConstraints(biometricInputParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.BiometricsPost(r.Context(), biometricInputParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}
