// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
)

// TrainingAPIController binds http requests to an api service and writes the service results to the http response
type TrainingAPIController struct {
	service      TrainingAPIServicer
	errorHandler ErrorHandler
}

// TrainingAPIOption for how the controller is set up.
type TrainingAPIOption func(*TrainingAPIController)

// WithTrainingAPIErrorHandler inject ErrorHandler into controller
func WithTrainingAPIErrorHandler(h ErrorHandler) TrainingAPIOption {
	return func(c *TrainingAPIController) {
		c.errorHandler = h
	}
}

// NewTrainingAPIController creates a default api controller
func NewTrainingAPIController(s TrainingAPIServicer, opts ...TrainingAPIOption) *TrainingAPIController {
	controller := &TrainingAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the TrainingAPIController
func (c *TrainingAPIController) Routes() Routes {
	return Routes{
		"GetTrainingPlansPost": Route{
			strings.ToUpper("Post"),
			"/api/v1/get-training-plans",
			c.GetTrainingPlansPost,
		},
		"TrainingPlansItemsItemIdDelete": Route{
			strings.ToUpper("Delete"),
			"/api/v1/training-plans/items/{item_id}",
			c.TrainingPlansItemsItemIdDelete,
		},
		"TrainingPlansItemsItemIdOverridePost": Route{
			strings.ToUpper("Post"),
			"/api/v1/training-plans/items/{item_id}/override",
			c.TrainingPlansItemsItemIdOverridePost,
		},
		"TrainingPlansPlanIdAssignPost": Route{
			strings.ToUpper("Post"),
			"/api/v1/training-plans/{plan_id}/assign",
			c.TrainingPlansPlanIdAssignPost,
		},
		"TrainingPlansPlanIdItemsPost": Route{
			strings.ToUpper("Post"),
			"/api/v1/training-plans/{plan_id}/items",
			c.TrainingPlansPlanIdItemsPost,
		},
		"TrainingPlansPost": Route{
			strings.ToUpper("Post"),
			"/api/v1/training-plans",
			c.TrainingPlansPost,
		},
	}
}

// GetTrainingPlansPost - Список тренировочных планов
func (c *TrainingAPIController) GetTrainingPlansPost(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetTrainingPlansPost(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// TrainingPlansItemsItemIdDelete - Удаление пункта плана
func (c *TrainingAPIController) TrainingPlansItemsItemIdDelete(w http.ResponseWriter, r *http.Request) {
	itemIdParam, err := parseNumericParameter[int32](
		chi.URLParam(r, "item_id"),
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "item_id", Err: err}, nil)
		return
	}
	result, err := c.service.TrainingPlansItemsItemIdDelete(r.Context(), itemIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// TrainingPlansItemsItemIdOverridePost - Изменение пункта плана для конкретного спортсмена
func (c *TrainingAPIController) TrainingPlansItemsItemIdOverridePost(w http.ResponseWriter, r *http.Request) {
	itemIdParam, err := parseNumericParameter[int32](
		chi.URLParam(r, "item_id"),
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "item_id", Err: err}, nil)
		return
	}
	trainingPlansItemsItemIdOverridePostRequestParam := TrainingPlansItemsItemIdOverridePostRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&trainingPlansItemsItemIdOverridePostRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTrainingPlansItemsItemIdOverridePostRequestRequired(trainingPlansItemsItemIdOverridePostRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTrainingPlansItemsItemIdOverridePostRequestConstraints(trainingPlansItemsItemIdOverridePostRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.TrainingPlansItemsItemIdOverridePost(r.Context(), itemIdParam, trainingPlansItemsItemIdOverridePostRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// TrainingPlansPlanIdAssignPost - Назначить план спортсменам
func (c *TrainingAPIController) TrainingPlansPlanIdAssignPost(w http.ResponseWriter, r *http.Request) {
	planIdParam, err := parseNumericParameter[int32](
		chi.URLParam(r, "plan_id"),
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "plan_id", Err: err}, nil)
		return
	}
	trainingPlansPlanIdAssignPostRequestParam := TrainingPlansPlanIdAssignPostRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&trainingPlansPlanIdAssignPostRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTrainingPlansPlanIdAssignPostRequestRequired(trainingPlansPlanIdAssignPostRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTrainingPlansPlanIdAssignPostRequestConstraints(trainingPlansPlanIdAssignPostRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.TrainingPlansPlanIdAssignPost(r.Context(), planIdParam, trainingPlansPlanIdAssignPostRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// TrainingPlansPlanIdItemsPost - Добавление пункта в план
func (c *TrainingAPIController) TrainingPlansPlanIdItemsPost(w http.ResponseWriter, r *http.Request) {
	planIdParam, err := parseNumericParameter[int32](
		chi.URLParam(r, "plan_id"),
		WithRequire[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "plan_id", Err: err}, nil)
		return
	}
	trainingPlanItemCreateParam := TrainingPlanItemCreate{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&trainingPlanItemCreateParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTrainingPlanItemCreateRequired(trainingPlanItemCreateParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTrainingPlanItemCreateConstraints(trainingPlanItemCreateParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.TrainingPlansPlanIdItemsPost(r.Context(), planIdParam, trainingPlanItemCreateParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// TrainingPlansPost - Создание тренировочного плана
func (c *TrainingAPIController) TrainingPlansPost(w http.ResponseWriter, r *http.Request) {
	trainingPlanCreateParam := TrainingPlanCreate{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&trainingPlanCreateParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTrainingPlanCreateRequired(trainingPlanCreateParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTrainingPlanCreateConstraints(trainingPlanCreateParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.TrainingPlansPost(r.Context(), trainingPlanCreateParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}
