// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// AuthAPIController binds http requests to an api service and writes the service results to the http response
type AuthAPIController struct {
	service      AuthAPIServicer
	errorHandler ErrorHandler
}

// AuthAPIOption for how the controller is set up.
type AuthAPIOption func(*AuthAPIController)

// WithAuthAPIErrorHandler inject ErrorHandler into controller
func WithAuthAPIErrorHandler(h ErrorHandler) AuthAPIOption {
	return func(c *AuthAPIController) {
		c.errorHandler = h
	}
}

// NewAuthAPIController creates a default api controller
func NewAuthAPIController(s AuthAPIServicer, opts ...AuthAPIOption) *AuthAPIController {
	controller := &AuthAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AuthAPIController
func (c *AuthAPIController) Routes() Routes {
	return Routes{
		"AuthAthleteProfilePost": Route{
			strings.ToUpper("Post"),
			"/api/v1/auth/athlete-profile",
			c.AuthAthleteProfilePost,
		},
		"AuthAthleteTeamPost": Route{
			strings.ToUpper("Post"),
			"/api/v1/auth/athlete-team",
			c.AuthAthleteTeamPost,
		},
		"AuthCancelInvitePost": Route{
			strings.ToUpper("Post"),
			"/api/v1/auth/cancel-invite",
			c.AuthCancelInvitePost,
		},
		"AuthChangePasswordPost": Route{
			strings.ToUpper("Post"),
			"/api/v1/auth/change-password",
			c.AuthChangePasswordPost,
		},
		"AuthCreateInviteCodePost": Route{
			strings.ToUpper("Post"),
			"/api/v1/auth/create-invite-code",
			c.AuthCreateInviteCodePost,
		},
		"AuthGetAllInvitesGet": Route{
			strings.ToUpper("Get"),
			"/api/v1/auth/get-all-invites",
			c.AuthGetAllInvitesGet,
		},
		"AuthGetInviteDetailsPost": Route{
			strings.ToUpper("Post"),
			"/api/v1/auth/get-invite-details",
			c.AuthGetInviteDetailsPost,
		},
		"AuthLoginPost": Route{
			strings.ToUpper("Post"),
			"/api/v1/auth/login",
			c.AuthLoginPost,
		},
		"AuthRegisterAthletePost": Route{
			strings.ToUpper("Post"),
			"/api/v1/auth/register/athlete",
			c.AuthRegisterAthletePost,
		},
		"AuthRegisterInvitePost": Route{
			strings.ToUpper("Post"),
			"/api/v1/auth/register/invite",
			c.AuthRegisterInvitePost,
		},
	}
}

// AuthAthleteProfilePost - Профиль спортсмена
func (c *AuthAPIController) AuthAthleteProfilePost(w http.ResponseWriter, r *http.Request) {
	athleteProfileRequestParam := AthleteProfileRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&athleteProfileRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertAthleteProfileRequestRequired(athleteProfileRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertAthleteProfileRequestConstraints(athleteProfileRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthAthleteProfilePost(r.Context(), athleteProfileRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// AuthAthleteTeamPost - Команда спортсмена
func (c *AuthAPIController) AuthAthleteTeamPost(w http.ResponseWriter, r *http.Request) {
	athleteProfileRequestParam := AthleteProfileRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&athleteProfileRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertAthleteProfileRequestRequired(athleteProfileRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertAthleteProfileRequestConstraints(athleteProfileRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthAthleteTeamPost(r.Context(), athleteProfileRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// AuthCancelInvitePost - Отмена инвайта
func (c *AuthAPIController) AuthCancelInvitePost(w http.ResponseWriter, r *http.Request) {
	inviteCancelRequestParam := InviteCancelRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&inviteCancelRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertInviteCancelRequestRequired(inviteCancelRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertInviteCancelRequestConstraints(inviteCancelRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthCancelInvitePost(r.Context(), inviteCancelRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// AuthChangePasswordPost - Смена пароля пользователя
func (c *AuthAPIController) AuthChangePasswordPost(w http.ResponseWriter, r *http.Request) {
	authChangePasswordPostRequestParam := AuthChangePasswordPostRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&authChangePasswordPostRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertAuthChangePasswordPostRequestRequired(authChangePasswordPostRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertAuthChangePasswordPostRequestConstraints(authChangePasswordPostRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthChangePasswordPost(r.Context(), authChangePasswordPostRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// AuthCreateInviteCodePost - Создание инвайта для врача или тренера
func (c *AuthAPIController) AuthCreateInviteCodePost(w http.ResponseWriter, r *http.Request) {
	inviteCreateRequestParam := InviteCreateRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&inviteCreateRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertInviteCreateRequestRequired(inviteCreateRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertInviteCreateRequestConstraints(inviteCreateRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthCreateInviteCodePost(r.Context(), inviteCreateRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// AuthGetAllInvitesGet - Все инвайты
func (c *AuthAPIController) AuthGetAllInvitesGet(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.AuthGetAllInvitesGet(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// AuthGetInviteDetailsPost - Информация о приглашении
func (c *AuthAPIController) AuthGetInviteDetailsPost(w http.ResponseWriter, r *http.Request) {
	inviteDetailsRequestParam := InviteDetailsRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&inviteDetailsRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertInviteDetailsRequestRequired(inviteDetailsRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertInviteDetailsRequestConstraints(inviteDetailsRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthGetInviteDetailsPost(r.Context(), inviteDetailsRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// AuthLoginPost - Авторизация
func (c *AuthAPIController) AuthLoginPost(w http.ResponseWriter, r *http.Request) {
	loginRequestParam := LoginRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&loginRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertLoginRequestRequired(loginRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertLoginRequestConstraints(loginRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthLoginPost(r.Context(), loginRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// AuthRegisterAthletePost - Регистрация спортсмена
func (c *AuthAPIController) AuthRegisterAthletePost(w http.ResponseWriter, r *http.Request) {
	athleteRegisterRequestParam := AthleteRegisterRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&athleteRegisterRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertAthleteRegisterRequestRequired(athleteRegisterRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertAthleteRegisterRequestConstraints(athleteRegisterRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthRegisterAthletePost(r.Context(), athleteRegisterRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}

// AuthRegisterInvitePost - Регистрация по инвайт-коду (для тренеров и врачей)
func (c *AuthAPIController) AuthRegisterInvitePost(w http.ResponseWriter, r *http.Request) {
	inviteRegisterRequestParam := InviteRegisterRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&inviteRegisterRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertInviteRegisterRequestRequired(inviteRegisterRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertInviteRegisterRequestConstraints(inviteRegisterRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.AuthRegisterInvitePost(r.Context(), inviteRegisterRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)
}
