// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

// ImplResponse defines an implementation response with error code and the associated body
type ImplResponse struct {
	Code    int
	Headers map[string][]string
	Body    interface{}
}
