// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TrainingPlanItemCreate struct {
	WorkoutDate string `json:"workout_date"`

	Time string `json:"time"`

	SessionTypeId int32 `json:"session_type_id"`

	FormatTypeId int32 `json:"format_type_id"`

	Value int32 `json:"value"`

	Description string `json:"description,omitempty"`
}

// AssertTrainingPlanItemCreateRequired checks if the required fields are not zero-ed
func AssertTrainingPlanItemCreateRequired(obj TrainingPlanItemCreate) error {
	elements := map[string]interface{}{
		"workout_date":    obj.WorkoutDate,
		"time":            obj.Time,
		"session_type_id": obj.SessionTypeId,
		"format_type_id":  obj.FormatTypeId,
		"value":           obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTrainingPlanItemCreateConstraints checks if the values respects the defined constraints
func AssertTrainingPlanItemCreateConstraints(obj TrainingPlanItemCreate) error {
	return nil
}
