// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamJoinRequest struct {
	TeamId int32 `json:"team_id,omitempty"`
}

// AssertTeamJoinRequestRequired checks if the required fields are not zero-ed
func AssertTeamJoinRequestRequired(obj TeamJoinRequest) error {
	return nil
}

// AssertTeamJoinRequestConstraints checks if the values respects the defined constraints
func AssertTeamJoinRequestConstraints(obj TeamJoinRequest) error {
	return nil
}
