// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type AthleteProfileRequest struct {
	AthleteId int32 `json:"athlete_id,omitempty"`

	TeamId int32 `json:"team_id,omitempty"`
}

// AssertAthleteProfileRequestRequired checks if the required fields are not zero-ed
func AssertAthleteProfileRequestRequired(obj AthleteProfileRequest) error {
	return nil
}

// AssertAthleteProfileRequestConstraints checks if the values respects the defined constraints
func AssertAthleteProfileRequestConstraints(obj AthleteProfileRequest) error {
	return nil
}
