// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamGetMedicalstaffResponse struct {
	Medicalstaff []MedicalstaffProfileResponse `json:"medicalstaff,omitempty"`
}

// AssertTeamGetMedicalstaffResponseRequired checks if the required fields are not zero-ed
func AssertTeamGetMedicalstaffResponseRequired(obj TeamGetMedicalstaffResponse) error {
	for _, el := range obj.Medicalstaff {
		if err := AssertMedicalstaffProfileResponseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTeamGetMedicalstaffResponseConstraints checks if the values respects the defined constraints
func AssertTeamGetMedicalstaffResponseConstraints(obj TeamGetMedicalstaffResponse) error {
	for _, el := range obj.Medicalstaff {
		if err := AssertMedicalstaffProfileResponseConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
