// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamRequest struct {
	TeamId int32 `json:"team_id,omitempty"`
}

// AssertTeamRequestRequired checks if the required fields are not zero-ed
func AssertTeamRequestRequired(obj TeamRequest) error {
	return nil
}

// AssertTeamRequestConstraints checks if the values respects the defined constraints
func AssertTeamRequestConstraints(obj TeamRequest) error {
	return nil
}
