// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type AthleteTeamResponse struct {
	TeamName string `json:"team_name,omitempty"`

	SportType string `json:"sport_type,omitempty"`
}

// AssertAthleteTeamResponseRequired checks if the required fields are not zero-ed
func AssertAthleteTeamResponseRequired(obj AthleteTeamResponse) error {
	return nil
}

// AssertAthleteTeamResponseConstraints checks if the values respects the defined constraints
func AssertAthleteTeamResponseConstraints(obj AthleteTeamResponse) error {
	return nil
}
