// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type InviteCreateRequest struct {
	Email string `json:"email"`

	Role string `json:"role"`

	FullName string `json:"full_name"`

	LicenseNumber string `json:"license_number"`

	OrganizationId int32 `json:"organization_id"`
}

// AssertInviteCreateRequestRequired checks if the required fields are not zero-ed
func AssertInviteCreateRequestRequired(obj InviteCreateRequest) error {
	elements := map[string]interface{}{
		"email":           obj.Email,
		"role":            obj.Role,
		"full_name":       obj.FullName,
		"license_number":  obj.LicenseNumber,
		"organization_id": obj.OrganizationId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertInviteCreateRequestConstraints checks if the values respects the defined constraints
func AssertInviteCreateRequestConstraints(obj InviteCreateRequest) error {
	return nil
}
