// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamGetMedicalAssignmentsResponse struct {
	Athletes []MedicalAssigment `json:"athletes,omitempty"`
}

// AssertTeamGetMedicalAssignmentsResponseRequired checks if the required fields are not zero-ed
func AssertTeamGetMedicalAssignmentsResponseRequired(obj TeamGetMedicalAssignmentsResponse) error {
	for _, el := range obj.Athletes {
		if err := AssertMedicalAssigmentRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTeamGetMedicalAssignmentsResponseConstraints checks if the values respects the defined constraints
func AssertTeamGetMedicalAssignmentsResponseConstraints(obj TeamGetMedicalAssignmentsResponse) error {
	for _, el := range obj.Athletes {
		if err := AssertMedicalAssigmentConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
