// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type InviteCreateResponse struct {
	InviteCode string `json:"invite_code,omitempty"`

	Url string `json:"url,omitempty"`
}

// AssertInviteCreateResponseRequired checks if the required fields are not zero-ed
func AssertInviteCreateResponseRequired(obj InviteCreateResponse) error {
	return nil
}

// AssertInviteCreateResponseConstraints checks if the values respects the defined constraints
func AssertInviteCreateResponseConstraints(obj InviteCreateResponse) error {
	return nil
}
