// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TrainingPlan struct {
	PlanId int32 `json:"plan_id,omitempty"`

	Title string `json:"title,omitempty"`

	TeamName string `json:"team_name,omitempty"`

	StartDate string `json:"start_date,omitempty"`

	EndDate string `json:"end_date,omitempty"`

	Status string `json:"status,omitempty"`

	Description string `json:"description,omitempty"`
}

// AssertTrainingPlanRequired checks if the required fields are not zero-ed
func AssertTrainingPlanRequired(obj TrainingPlan) error {
	return nil
}

// AssertTrainingPlanConstraints checks if the values respects the defined constraints
func AssertTrainingPlanConstraints(obj TrainingPlan) error {
	return nil
}
