// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type CriticalAthleteProfileResponse struct {
	AthleteId int32 `json:"athlete_id,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	MiddleName string `json:"middle_name,omitempty"`

	TeamName string `json:"team_name,omitempty"`

	PeriodType string `json:"period_type,omitempty"`

	Indicators []AthleteIndicatorResponse `json:"indicators,omitempty"`

	Limits map[string]IndicatorLimit `json:"limits,omitempty"`
}

// AssertCriticalAthleteProfileResponseRequired checks if the required fields are not zero-ed
func AssertCriticalAthleteProfileResponseRequired(obj CriticalAthleteProfileResponse) error {
	for _, el := range obj.Indicators {
		if err := AssertAthleteIndicatorResponseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCriticalAthleteProfileResponseConstraints checks if the values respects the defined constraints
func AssertCriticalAthleteProfileResponseConstraints(obj CriticalAthleteProfileResponse) error {
	for _, el := range obj.Indicators {
		if err := AssertAthleteIndicatorResponseConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
