// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type Team struct {
	TeamId int32 `json:"team_id"`

	TeamName string `json:"team_name"`

	SportType string `json:"sport_type"`

	CountAthletes int32 `json:"count_athletes"`
}

// AssertTeamRequired checks if the required fields are not zero-ed
func AssertTeamRequired(obj Team) error {
	elements := map[string]interface{}{
		"team_id":        obj.TeamId,
		"team_name":      obj.TeamName,
		"sport_type":     obj.SportType,
		"count_athletes": obj.CountAthletes,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTeamConstraints checks if the values respects the defined constraints
func AssertTeamConstraints(obj Team) error {
	return nil
}
