// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamResponse struct {
	Teams []Team `json:"teams,omitempty"`
}

// AssertTeamResponseRequired checks if the required fields are not zero-ed
func AssertTeamResponseRequired(obj TeamResponse) error {
	for _, el := range obj.Teams {
		if err := AssertTeamRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTeamResponseConstraints checks if the values respects the defined constraints
func AssertTeamResponseConstraints(obj TeamResponse) error {
	for _, el := range obj.Teams {
		if err := AssertTeamConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
