// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type InviteDetailsRequest struct {
	InviteCode string `json:"invite_code,omitempty"`
}

// AssertInviteDetailsRequestRequired checks if the required fields are not zero-ed
func AssertInviteDetailsRequestRequired(obj InviteDetailsRequest) error {
	return nil
}

// AssertInviteDetailsRequestConstraints checks if the values respects the defined constraints
func AssertInviteDetailsRequestConstraints(obj InviteDetailsRequest) error {
	return nil
}
