// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type InviteCancelRequest struct {
	InviteId int32 `json:"invite_id,omitempty"`
}

// AssertInviteCancelRequestRequired checks if the required fields are not zero-ed
func AssertInviteCancelRequestRequired(obj InviteCancelRequest) error {
	return nil
}

// AssertInviteCancelRequestConstraints checks if the values respects the defined constraints
func AssertInviteCancelRequestConstraints(obj InviteCancelRequest) error {
	return nil
}
