// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type BiometricInput struct {
	Date string `json:"date"`

	MorningPulse int32 `json:"morning_pulse"`

	EveningPulse int32 `json:"evening_pulse"`

	HRV int32 `json:"HRV"`

	Weight float32 `json:"weight"`
}

// AssertBiometricInputRequired checks if the required fields are not zero-ed
func AssertBiometricInputRequired(obj BiometricInput) error {
	elements := map[string]interface{}{
		"date":          obj.Date,
		"morning_pulse": obj.MorningPulse,
		"evening_pulse": obj.EveningPulse,
		"HRV":           obj.HRV,
		"weight":        obj.Weight,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBiometricInputConstraints checks if the values respects the defined constraints
func AssertBiometricInputConstraints(obj BiometricInput) error {
	return nil
}
