// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type InviteAllResponse struct {
	Invites []InviteDetailsResponse `json:"invites,omitempty"`
}

// AssertInviteAllResponseRequired checks if the required fields are not zero-ed
func AssertInviteAllResponseRequired(obj InviteAllResponse) error {
	for _, el := range obj.Invites {
		if err := AssertInviteDetailsResponseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertInviteAllResponseConstraints checks if the values respects the defined constraints
func AssertInviteAllResponseConstraints(obj InviteAllResponse) error {
	for _, el := range obj.Invites {
		if err := AssertInviteDetailsResponseConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
