// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type IndicatorLimit struct {
	Min float32 `json:"min,omitempty"`

	Max float32 `json:"max,omitempty"`
}

// AssertIndicatorLimitRequired checks if the required fields are not zero-ed
func AssertIndicatorLimitRequired(obj IndicatorLimit) error {
	return nil
}

// AssertIndicatorLimitConstraints checks if the values respects the defined constraints
func AssertIndicatorLimitConstraints(obj IndicatorLimit) error {
	return nil
}
