// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type CriticalAthleteResponse struct {
	PeriodType string `json:"period_type,omitempty"`

	Indicators []AthleteIndicatorResponse `json:"indicators,omitempty"`

	Limits map[string]IndicatorLimit `json:"limits,omitempty"`
}

// AssertCriticalAthleteResponseRequired checks if the required fields are not zero-ed
func AssertCriticalAthleteResponseRequired(obj CriticalAthleteResponse) error {
	for _, el := range obj.Indicators {
		if err := AssertAthleteIndicatorResponseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCriticalAthleteResponseConstraints checks if the values respects the defined constraints
func AssertCriticalAthleteResponseConstraints(obj CriticalAthleteResponse) error {
	for _, el := range obj.Indicators {
		if err := AssertAthleteIndicatorResponseConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
