// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type CriticalAthleteRequest struct {
	AthleteId int32 `json:"athlete_id,omitempty"`
}

// AssertCriticalAthleteRequestRequired checks if the required fields are not zero-ed
func AssertCriticalAthleteRequestRequired(obj CriticalAthleteRequest) error {
	return nil
}

// AssertCriticalAthleteRequestConstraints checks if the values respects the defined constraints
func AssertCriticalAthleteRequestConstraints(obj CriticalAthleteRequest) error {
	return nil
}
