// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type MedicalAssigment struct {
	AthleteId int32 `json:"athlete_id,omitempty"`

	AthleteCode string `json:"athlete_code,omitempty"`

	AssignedBy int32 `json:"assigned_by,omitempty"`

	Age int32 `json:"age,omitempty"`

	SportType string `json:"sport_type,omitempty"`

	Status string `json:"status,omitempty"`
}

// AssertMedicalAssigmentRequired checks if the required fields are not zero-ed
func AssertMedicalAssigmentRequired(obj MedicalAssigment) error {
	return nil
}

// AssertMedicalAssigmentConstraints checks if the values respects the defined constraints
func AssertMedicalAssigmentConstraints(obj MedicalAssigment) error {
	return nil
}
