// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type InviteRegisterRequest struct {
	InviteCode string `json:"invite_code"`

	Email string `json:"email"`

	Phone string `json:"phone,omitempty"`

	Password string `json:"password"`

	Role string `json:"role"`

	FirstName string `json:"first_name"`

	LastName string `json:"last_name"`

	MiddleName string `json:"middle_name"`

	LicenseNumber string `json:"license_number"`

	OrganizationId int32 `json:"organization_id,omitempty"`

	SportTypeId int32 `json:"sport_type_id,omitempty"`

	Specialization string `json:"specialization,omitempty"`

	ExperienceLevel string `json:"experience_level,omitempty"`
}

// AssertInviteRegisterRequestRequired checks if the required fields are not zero-ed
func AssertInviteRegisterRequestRequired(obj InviteRegisterRequest) error {
	elements := map[string]interface{}{
		"invite_code":    obj.InviteCode,
		"email":          obj.Email,
		"password":       obj.Password,
		"role":           obj.Role,
		"first_name":     obj.FirstName,
		"last_name":      obj.LastName,
		"middle_name":    obj.MiddleName,
		"license_number": obj.LicenseNumber,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertInviteRegisterRequestConstraints checks if the values respects the defined constraints
func AssertInviteRegisterRequestConstraints(obj InviteRegisterRequest) error {
	return nil
}
