// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type CriticalAthletesResponse struct {
	Athletes []CriticalAthleteProfileResponse `json:"athletes,omitempty"`
}

// AssertCriticalAthletesResponseRequired checks if the required fields are not zero-ed
func AssertCriticalAthletesResponseRequired(obj CriticalAthletesResponse) error {
	for _, el := range obj.Athletes {
		if err := AssertCriticalAthleteProfileResponseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCriticalAthletesResponseConstraints checks if the values respects the defined constraints
func AssertCriticalAthletesResponseConstraints(obj CriticalAthletesResponse) error {
	for _, el := range obj.Athletes {
		if err := AssertCriticalAthleteProfileResponseConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
