// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamCreateRequest struct {
	TeamName string `json:"team_name,omitempty"`

	SportTypeId int32 `json:"sport_type_id,omitempty"`
}

// AssertTeamCreateRequestRequired checks if the required fields are not zero-ed
func AssertTeamCreateRequestRequired(obj TeamCreateRequest) error {
	return nil
}

// AssertTeamCreateRequestConstraints checks if the values respects the defined constraints
func AssertTeamCreateRequestConstraints(obj TeamCreateRequest) error {
	return nil
}
