// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type MedicalstaffProfileResponse struct {
	MedicalstaffId int32 `json:"medicalstaff_id,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	MiddleName string `json:"middle_name,omitempty"`

	Specialization string `json:"specialization,omitempty"`
}

// AssertMedicalstaffProfileResponseRequired checks if the required fields are not zero-ed
func AssertMedicalstaffProfileResponseRequired(obj MedicalstaffProfileResponse) error {
	return nil
}

// AssertMedicalstaffProfileResponseConstraints checks if the values respects the defined constraints
func AssertMedicalstaffProfileResponseConstraints(obj MedicalstaffProfileResponse) error {
	return nil
}
