// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type InviteDetailsResponse struct {
	InviteId int32 `json:"invite_id,omitempty"`

	InviteCode string `json:"invite_code,omitempty"`

	Email string `json:"email,omitempty"`

	Role string `json:"role,omitempty"`

	LicenseNumber string `json:"license_number,omitempty"`

	OrganizationId int32 `json:"organization_id,omitempty"`

	IsUsed bool `json:"is_used,omitempty"`
}

// AssertInviteDetailsResponseRequired checks if the required fields are not zero-ed
func AssertInviteDetailsResponseRequired(obj InviteDetailsResponse) error {
	return nil
}

// AssertInviteDetailsResponseConstraints checks if the values respects the defined constraints
func AssertInviteDetailsResponseConstraints(obj InviteDetailsResponse) error {
	return nil
}
