// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TrainingPlansPlanIdItemsPostRequest struct {
	SessionDate string `json:"session_date"`

	SessionTypeId int32 `json:"session_type_id"`

	FormatTypeId int32 `json:"format_type_id"`

	Value string `json:"value"`

	Notes string `json:"notes,omitempty"`
}

// AssertTrainingPlansPlanIdItemsPostRequestRequired checks if the required fields are not zero-ed
func AssertTrainingPlansPlanIdItemsPostRequestRequired(obj TrainingPlansPlanIdItemsPostRequest) error {
	elements := map[string]interface{}{
		"session_date":    obj.SessionDate,
		"session_type_id": obj.SessionTypeId,
		"format_type_id":  obj.FormatTypeId,
		"value":           obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTrainingPlansPlanIdItemsPostRequestConstraints checks if the values respects the defined constraints
func AssertTrainingPlansPlanIdItemsPostRequestConstraints(obj TrainingPlansPlanIdItemsPostRequest) error {
	return nil
}
