// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TokenResponse struct {
	Role string `json:"role,omitempty"`

	AccessToken string `json:"access_token,omitempty"`

	RefreshToken string `json:"refresh_token,omitempty"`
}

// AssertTokenResponseRequired checks if the required fields are not zero-ed
func AssertTokenResponseRequired(obj TokenResponse) error {
	return nil
}

// AssertTokenResponseConstraints checks if the values respects the defined constraints
func AssertTokenResponseConstraints(obj TokenResponse) error {
	return nil
}
