// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type ReferAthletesToMedicalstaffRequest struct {
	Athletes []ReferAthlete `json:"athletes,omitempty"`
}

// AssertReferAthletesToMedicalstaffRequestRequired checks if the required fields are not zero-ed
func AssertReferAthletesToMedicalstaffRequestRequired(obj ReferAthletesToMedicalstaffRequest) error {
	for _, el := range obj.Athletes {
		if err := AssertReferAthleteRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertReferAthletesToMedicalstaffRequestConstraints checks if the values respects the defined constraints
func AssertReferAthletesToMedicalstaffRequestConstraints(obj ReferAthletesToMedicalstaffRequest) error {
	for _, el := range obj.Athletes {
		if err := AssertReferAthleteConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
