// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type AthleteRegisterRequest struct {
	Email string `json:"email"`

	Password string `json:"password"`

	FirstName string `json:"first_name"`

	LastName string `json:"last_name"`

	MiddleName string `json:"middle_name"`

	Gender string `json:"gender"`

	DateOfBirth string `json:"date_of_birth"`

	Phone string `json:"phone,omitempty"`
}

// AssertAthleteRegisterRequestRequired checks if the required fields are not zero-ed
func AssertAthleteRegisterRequestRequired(obj AthleteRegisterRequest) error {
	elements := map[string]interface{}{
		"email":         obj.Email,
		"password":      obj.Password,
		"first_name":    obj.FirstName,
		"last_name":     obj.LastName,
		"middle_name":   obj.MiddleName,
		"gender":        obj.Gender,
		"date_of_birth": obj.DateOfBirth,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAthleteRegisterRequestConstraints checks if the values respects the defined constraints
func AssertAthleteRegisterRequestConstraints(obj AthleteRegisterRequest) error {
	return nil
}
