// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamJoin struct {
	RequestId int32 `json:"request_id,omitempty"`

	SecondName string `json:"second_name,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	MiddleName string `json:"middle_name,omitempty"`

	Email string `json:"email,omitempty"`

	TeamName string `json:"team_name,omitempty"`

	RequestDate string `json:"request_date,omitempty"`

	Status string `json:"status,omitempty"`
}

// AssertTeamJoinRequired checks if the required fields are not zero-ed
func AssertTeamJoinRequired(obj TeamJoin) error {
	return nil
}

// AssertTeamJoinConstraints checks if the values respects the defined constraints
func AssertTeamJoinConstraints(obj TeamJoin) error {
	return nil
}
