// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type CoachProfileResponse struct {
	CoachId int32 `json:"coach_id"`

	RoleInTeam string `json:"role_in_team,omitempty"`

	FirstName string `json:"first_name"`

	LastName string `json:"last_name"`

	MiddleName string `json:"middle_name"`

	Email string `json:"email"`

	Phone string `json:"phone"`

	LicenseNumber string `json:"license_number,omitempty"`

	ExperienceLevel string `json:"experience_level,omitempty"`

	SportType string `json:"sport_type,omitempty"`
}

// AssertCoachProfileResponseRequired checks if the required fields are not zero-ed
func AssertCoachProfileResponseRequired(obj CoachProfileResponse) error {
	elements := map[string]interface{}{
		"coach_id":    obj.CoachId,
		"first_name":  obj.FirstName,
		"last_name":   obj.LastName,
		"middle_name": obj.MiddleName,
		"email":       obj.Email,
		"phone":       obj.Phone,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCoachProfileResponseConstraints checks if the values respects the defined constraints
func AssertCoachProfileResponseConstraints(obj CoachProfileResponse) error {
	return nil
}
