// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamJoinsListResponse struct {
	Joins []TeamJoin `json:"joins,omitempty"`
}

// AssertTeamJoinsListResponseRequired checks if the required fields are not zero-ed
func AssertTeamJoinsListResponseRequired(obj TeamJoinsListResponse) error {
	for _, el := range obj.Joins {
		if err := AssertTeamJoinRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTeamJoinsListResponseConstraints checks if the values respects the defined constraints
func AssertTeamJoinsListResponseConstraints(obj TeamJoinsListResponse) error {
	for _, el := range obj.Joins {
		if err := AssertTeamJoinConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
