// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TrainingPlansPlanIdAssignPostRequest struct {
	AthleteIds []int32 `json:"athlete_ids"`

	StartDate string `json:"start_date"`
}

// AssertTrainingPlansPlanIdAssignPostRequestRequired checks if the required fields are not zero-ed
func AssertTrainingPlansPlanIdAssignPostRequestRequired(obj TrainingPlansPlanIdAssignPostRequest) error {
	elements := map[string]interface{}{
		"athlete_ids": obj.AthleteIds,
		"start_date":  obj.StartDate,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTrainingPlansPlanIdAssignPostRequestConstraints checks if the values respects the defined constraints
func AssertTrainingPlansPlanIdAssignPostRequestConstraints(obj TrainingPlansPlanIdAssignPostRequest) error {
	return nil
}
