// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TrainingPlanCreate struct {
	Title string `json:"title"`

	TeamId int32 `json:"team_id"`

	Description string `json:"description,omitempty"`

	StartDate string `json:"start_date"`

	EndDate string `json:"end_date"`

	Status string `json:"status,omitempty"`

	PeriodTypeId int32 `json:"period_type_id"`
}

// AssertTrainingPlanCreateRequired checks if the required fields are not zero-ed
func AssertTrainingPlanCreateRequired(obj TrainingPlanCreate) error {
	elements := map[string]interface{}{
		"title":          obj.Title,
		"team_id":        obj.TeamId,
		"start_date":     obj.StartDate,
		"end_date":       obj.EndDate,
		"period_type_id": obj.PeriodTypeId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTrainingPlanCreateConstraints checks if the values respects the defined constraints
func AssertTrainingPlanCreateConstraints(obj TrainingPlanCreate) error {
	return nil
}
