// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type AthleteIndicatorResponse struct {
	Date string `json:"date,omitempty"`

	Hrv int32 `json:"hrv,omitempty"`

	MorningPulse int32 `json:"morning_pulse,omitempty"`

	EveningPulse int32 `json:"evening_pulse,omitempty"`

	Weight float32 `json:"weight,omitempty"`
}

// AssertAthleteIndicatorResponseRequired checks if the required fields are not zero-ed
func AssertAthleteIndicatorResponseRequired(obj AthleteIndicatorResponse) error {
	return nil
}

// AssertAthleteIndicatorResponseConstraints checks if the values respects the defined constraints
func AssertAthleteIndicatorResponseConstraints(obj AthleteIndicatorResponse) error {
	return nil
}
