// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type AuthChangePasswordPostRequest struct {
	OldPassword string `json:"old_password"`

	NewPassword string `json:"new_password"`
}

// AssertAuthChangePasswordPostRequestRequired checks if the required fields are not zero-ed
func AssertAuthChangePasswordPostRequestRequired(obj AuthChangePasswordPostRequest) error {
	elements := map[string]interface{}{
		"old_password": obj.OldPassword,
		"new_password": obj.NewPassword,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAuthChangePasswordPostRequestConstraints checks if the values respects the defined constraints
func AssertAuthChangePasswordPostRequestConstraints(obj AuthChangePasswordPostRequest) error {
	return nil
}
