// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TrainingPlansPostRequest struct {
	Name string `json:"name"`

	Description string `json:"description"`
}

// AssertTrainingPlansPostRequestRequired checks if the required fields are not zero-ed
func AssertTrainingPlansPostRequestRequired(obj TrainingPlansPostRequest) error {
	elements := map[string]interface{}{
		"name":        obj.Name,
		"description": obj.Description,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTrainingPlansPostRequestConstraints checks if the values respects the defined constraints
func AssertTrainingPlansPostRequestConstraints(obj TrainingPlansPostRequest) error {
	return nil
}
