// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamAthleteStatusResponse struct {
	RequestId int32 `json:"request_id,omitempty"`

	TeamName string `json:"team_name,omitempty"`

	RequestedAt string `json:"requested_at,omitempty"`

	Status string `json:"status,omitempty"`
}

// AssertTeamAthleteStatusResponseRequired checks if the required fields are not zero-ed
func AssertTeamAthleteStatusResponseRequired(obj TeamAthleteStatusResponse) error {
	return nil
}

// AssertTeamAthleteStatusResponseConstraints checks if the values respects the defined constraints
func AssertTeamAthleteStatusResponseConstraints(obj TeamAthleteStatusResponse) error {
	return nil
}
