// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TrainingPlanListResponse struct {
	Plans []TrainingPlan `json:"plans,omitempty"`
}

// AssertTrainingPlanListResponseRequired checks if the required fields are not zero-ed
func AssertTrainingPlanListResponseRequired(obj TrainingPlanListResponse) error {
	for _, el := range obj.Plans {
		if err := AssertTrainingPlanRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTrainingPlanListResponseConstraints checks if the values respects the defined constraints
func AssertTrainingPlanListResponseConstraints(obj TrainingPlanListResponse) error {
	for _, el := range obj.Plans {
		if err := AssertTrainingPlanConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
