// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamGetCoachesResponse struct {
	Coaches []CoachProfileResponse `json:"coaches,omitempty"`
}

// AssertTeamGetCoachesResponseRequired checks if the required fields are not zero-ed
func AssertTeamGetCoachesResponseRequired(obj TeamGetCoachesResponse) error {
	for _, el := range obj.Coaches {
		if err := AssertCoachProfileResponseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTeamGetCoachesResponseConstraints checks if the values respects the defined constraints
func AssertTeamGetCoachesResponseConstraints(obj TeamGetCoachesResponse) error {
	for _, el := range obj.Coaches {
		if err := AssertCoachProfileResponseConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
