// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type ReferAthlete struct {
	AthleteId int32 `json:"athlete_id,omitempty"`

	MedicalstaffId int32 `json:"medicalstaff_id,omitempty"`
}

// AssertReferAthleteRequired checks if the required fields are not zero-ed
func AssertReferAthleteRequired(obj ReferAthlete) error {
	return nil
}

// AssertReferAthleteConstraints checks if the values respects the defined constraints
func AssertReferAthleteConstraints(obj ReferAthlete) error {
	return nil
}
