// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TrainingPlansItemsItemIdOverridePostRequest struct {
	AthleteId int32 `json:"athlete_id"`

	CustomValue string `json:"custom_value"`

	CustomNotes string `json:"custom_notes,omitempty"`
}

// AssertTrainingPlansItemsItemIdOverridePostRequestRequired checks if the required fields are not zero-ed
func AssertTrainingPlansItemsItemIdOverridePostRequestRequired(obj TrainingPlansItemsItemIdOverridePostRequest) error {
	elements := map[string]interface{}{
		"athlete_id":   obj.AthleteId,
		"custom_value": obj.CustomValue,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTrainingPlansItemsItemIdOverridePostRequestConstraints checks if the values respects the defined constraints
func AssertTrainingPlansItemsItemIdOverridePostRequestConstraints(obj TrainingPlansItemsItemIdOverridePostRequest) error {
	return nil
}
