// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamsJoinPostRequest struct {
	TeamId int32 `json:"team_id"`
}

// AssertTeamsJoinPostRequestRequired checks if the required fields are not zero-ed
func AssertTeamsJoinPostRequestRequired(obj TeamsJoinPostRequest) error {
	elements := map[string]interface{}{
		"team_id": obj.TeamId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTeamsJoinPostRequestConstraints checks if the values respects the defined constraints
func AssertTeamsJoinPostRequestConstraints(obj TeamsJoinPostRequest) error {
	return nil
}
