// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type TeamGetAthletesResponse struct {
	Athletes []AthleteProfileResponse `json:"athletes,omitempty"`
}

// AssertTeamGetAthletesResponseRequired checks if the required fields are not zero-ed
func AssertTeamGetAthletesResponseRequired(obj TeamGetAthletesResponse) error {
	for _, el := range obj.Athletes {
		if err := AssertAthleteProfileResponseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTeamGetAthletesResponseConstraints checks if the values respects the defined constraints
func AssertTeamGetAthletesResponseConstraints(obj TeamGetAthletesResponse) error {
	for _, el := range obj.Athletes {
		if err := AssertAthleteProfileResponseConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
