// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type LoginResponse struct {
	Role string `json:"role,omitempty"`
}

// AssertLoginResponseRequired checks if the required fields are not zero-ed
func AssertLoginResponseRequired(obj LoginResponse) error {
	return nil
}

// AssertLoginResponseConstraints checks if the values respects the defined constraints
func AssertLoginResponseConstraints(obj LoginResponse) error {
	return nil
}
