// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type AthleteProfileResponse struct {
	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	MiddleName string `json:"middle_name,omitempty"`

	Email string `json:"email,omitempty"`

	DateOfBirth string `json:"date_of_birth,omitempty"`

	Phone string `json:"phone,omitempty"`
}

// AssertAthleteProfileResponseRequired checks if the required fields are not zero-ed
func AssertAthleteProfileResponseRequired(obj AthleteProfileResponse) error {
	return nil
}

// AssertAthleteProfileResponseConstraints checks if the values respects the defined constraints
func AssertAthleteProfileResponseConstraints(obj AthleteProfileResponse) error {
	return nil
}
