// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Спортивная система | API
 *
 * Система для регистрации, авторизации и управления ролями пользователей.
 *
 * API version: 1.0.0
 */

package openapi

type BiometricInput struct {
	Date string `json:"date"`

	TimeOfDay string `json:"time_of_day"`

	Time string `json:"time,omitempty"`

	Pulse int32 `json:"pulse,omitempty"`

	HRV int32 `json:"HRV,omitempty"`

	Weight float32 `json:"weight,omitempty"`
}

// AssertBiometricInputRequired checks if the required fields are not zero-ed
func AssertBiometricInputRequired(obj BiometricInput) error {
	elements := map[string]interface{}{
		"date":        obj.Date,
		"time_of_day": obj.TimeOfDay,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBiometricInputConstraints checks if the values respects the defined constraints
func AssertBiometricInputConstraints(obj BiometricInput) error {
	return nil
}
